### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by trypsynth** [codecat/angel#2]
Hi, is this project still being maintained/looked at all? Was some roadblock hit? I also really want to like Love, but the usage of Lua makes it kind of meh for me. Also how easy that makes it to be decompiled...

**Comment by codecat** [comment]
Cool to see there's some interest in this! I haven't looked at this in years, as you can tell. I think the idea of it is interesting though, and I'm sure there's better ways of doing this now.

However if you're looking for something that's not super decompilable, Angelscript only really helps you there to a certain degree as it compiles down to bytecode. I'm not aware of any existing decompiler for it but I expect it to be relatively trivial.

**Comment by trypsynth** [comment]
Decompilation isn't the only reason, although it does kind of rub me the wrong way that if I send my game to someone, they can literally open it in 7z, edit the code, and re-run the game right then and there. I also just like Angelscript, and am currently trying to build an audiogame framework on top of it, but Love seems really nice, so figured I'd see what's up with this project.

**Comment by codecat** [comment]
I see! Well, I haven't worked on this in ages, but indeed; Angelscript is awesome (I still use it every day) and I'd love to see this project become more of a reality at some point, but as it stands I don't have a lot of time to work on it myself right now.

**Comment by trypsynth** [comment]
Ah, fair enough. Thanks for your time :)
